/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.3/userguide/building_swift_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "ADA_1042_AQ1_SB_CartaoService_MSNOTIFICACAO"
include("app:domain")
findProject(":app:domain")?.name = "domain"
include("app:application")
findProject(":app:application")?.name = "application"
include("app:infrastructure")
findProject(":app:infrastructure")?.name = "infrastructure"
